### PR TITLE
Canary expects services to be a subclass of Ember.Service

### PR DESCRIPTION
**Pull request by salzhrani**
Fails in canary

### CODE REVIEW

**Comment by ef4** [comment]
Thanks!

**Comment by truenorth** [comment]
Thanks for this! It was biting me this morning

**Comment by salzhrani** [comment]
can we have a release please ?

**Comment by peec** [comment]
I just upgraded to canary myself, and it would be good if this got released -  liquid breaks my app if this fix is not added.

For now:

    "liquid-fire": "git+https://github.com/ef4/liquid-fire.git#386e5594574578166fce1edf0689329e802b1444"

**Comment by rlivsey** [comment]
On canary this check is now a deprecation instead of an assert, so updating canary will also fix your app until a new version if liquid-fire is cut.

https://github.com/emberjs/ember.js/pull/11300

**Pull request merged**
