### PR TITLE
Switching to outerHeight / outerWidth for explode / flyTo.

### PR DESCRIPTION
**Pull request by green-arrow**
Addresses #205

### CODE REVIEW

**Comment by ef4** [comment]
Thanks for the PR.

This seems to correct some cases but not all. We're now measuring `outerWidth` but still setting `width`. This will appear to work correctly when using `box-sizing: border-box`, but it will cause a jump when using the default box-sizing.

**Comment by ef4** [comment]
The above commit fixes `explode`. 

We still need an equivalent change in `fly-to`. That will be much easier to do if we can land this PR in Velocity: https://github.com/julianshapiro/velocity/pull/485

**Comment by green-arrow** [comment]
:+1: on the Velocity PR. I would suggest waiting on that to make it through before tackling `fly-to`.

**Comment by ef4** [comment]
Closed via 8622f078a9558bd08ed4786dc9051158f0738f23

**Pull request closed without merging**
