### PR TITLE
Adds a liquid-animating class while an animation is occuring

### PR DESCRIPTION
**Pull request by jdmaurer**
Allows for customization of liquid-container's CSS whilst it's children are animating. Can be used to control the element's overflow properties as described in issue #208.

### CODE REVIEW

**Comment by ef4** [comment]
Thanks for this PR.

This doesn't quite solve the problem in all cases, because `animate` is an optional helper. People are free to implement transitions in other ways.

Instead, take a look at `willTransition` and `afterTransition` in liquid-container.js. I think if you set and clear the class from there it will work in every case.

**Comment by jdmaurer** [comment]
I moved the changes into liquid-container.js, and it seems to be working as intended.

**Comment by ef4** [comment]
Thanks. I merged and then refactored a bit to take advantage of ember's built-in classNameBindings.

**Comment by grabbou** [comment]
Any chances getting this class on the entire html as well? Would be nice to set overflow: hidden to body when using `toUp` / `toDown` to prevent scrollbar appearing on OS X.

**Comment by TeknoFiend** [comment]
I'm missing how this solves #208. Is the idea that you override/disable `overflow:hidden` on the `liquid-outlet` then only have `overflow:hidden` on the `liquid-animating` class?

**Pull request merged**
