### PR TITLE
Adds documentation for transitions for empty outlets

### PR DESCRIPTION
**Pull request by twokul**

### CODE REVIEW

**Comment by ef4** [comment]
Thanks for documenting this. 

I think a better place for this information would be [this page](http://ef4.github.io/liquid-fire/#/transition-map/route-constraints), because that's where we talk about the rules for matching outlet transitions.

**Comment by twokul** [comment]
@ef4 will move

**Comment by twokul** [comment]
@ef4 moved. I'll be more than happy to tweak the wording if needed.

**Comment by ef4** [comment]
Thanks.

**Pull request merged**
