### PR TITLE
Update to support canary

### PR DESCRIPTION
**Pull request by rlivsey**
Supports canary with backwards compatibility with current versions.

### CODE REVIEW

**Comment by rlivsey** [comment]
There's still failures on the `with` helper, but that's unrelated to this change. 

If I get a chance I'll look into those failures this evening and amend (and rename) this pull request to get full canary compatibility.

**Comment by rlivsey** [comment]
@ef4 - I've done some more investigating into the failures:

Some of the failures are coming from ember-data, which we're not using, it's just a default dep for ember-cli addons. Removing ember-data as a dev dependency clears up all the "Teardown failed: Requested keys of a value that is not an object" errors. Updating to the latest version of data might also resolve these, but it was simpler to remove and move on!

That mostly just leaves the `liquid-with` helper errors. I *think* the `with.helperFunction` params is now expecting a stream to be passed in instead of the property name [here](https://github.com/ef4/liquid-fire/blob/master/app/helpers/with-apply.js#L50). I had similar issues with the `if` helper in my `ember-can` addon.

Changing that to use a stream gets us a step closer:

```javascript
env.helpers.with.helperFunction.call(this, [view.getStream(withArgs[0])], hash, options, env);
```

That gets rid of the errors, but it still doesn't actually work! Now we're pretty much at the limits of my understanding of how the underlying `with` helpers work and what values they are expecting. 

I'll try and put aside some more time this afternoon / evening but any help here would be welcome as I think it's fairly close!

**Comment by rlivsey** [comment]
Ooh, I imagine that some of these failures are related to [transform-with-as-to-hash.js](https://github.com/emberjs/ember.js/blob/4a1010a490c09dc4d662d22b229523c8f8734f82/packages/ember-template-compiler/lib/plugins/transform-with-as-to-hash.js) which transforms the HTMBars AST for `with`.

It converts 
```handlebars
{{#with foo.bar as bar}}
{{/with}}
```
to:
```handlebars
{{#with foo.bar as |bar|}}
{{/with}}
```

This obviously doesn't apply to `liquid-with` so it's not being transformed into the new format.

This starts to make sense, as I'd noticed that we were getting deprecation warnings for the 'context switching'  form of `with` when we weren't using that. This is because the with helper is [checking for block params here](https://github.com/emberjs/ember.js/blob/4a1010a490c09dc4d662d22b229523c8f8734f82/packages/ember-htmlbars/lib/helpers/with.js#L70) and we're not using the block syntax.

I wonder if we can extend that to apply to `liquid-with` too?

/me goes deeper down the rabbit hole.

**Comment by rlivsey** [comment]
That seems to have done the trick, I've added an AST transform for HTMLBars which does the same as the `{{with}}` transform.

All the demos work now but some tests still fail because they are using `Ember.Handlebars.compile` directly, which I don't think has the transform applied.

A little more investigation to go, but the end of the tunnel is in sight!

**Comment by ef4** [comment]
Awesome work @rlivsey!

**Comment by rlivsey** [comment]
The AST transform needs to happen in Node-land, for now I've done the equivalent in the client with a hacky regex but ideally we'd run it through a pre-compiler so it's like-for-like. 

I'm not aware of a HTMLBars equivalent to something like broccoli-ember-inline-template-compiler but I'm sure it wouldn't be too difficult to make one if needed.

**Comment by rlivsey** [comment]
Woop, it's all green! Many thanks to @rwjblue for pointing me in the right direction with the AST stuff.

**Comment by ef4** [comment]
:+1:

**Pull request merged**
