### PR TITLE
Adds a `media` constraint for matching transitions by media query

### PR DESCRIPTION
**Pull request by mattgrannary**
This is a simple but powerful feature that enables transitions to be conditionally run based on a given media query as discussed in #64 . The query is set up as a constraint and run with the `window.matchMedia` method.

Example:
```javascript
// Will run on small screen mobile devices
this.transition(
  this.toRoute('foo'),
  this.use('toLeft'),
  this.media('(max-width: 320px)')
);

// Will run on all other screen sizes
this.transition(
  this.toRoute('foo'),
  this.use('fade'),
  this.media('(min-width: 321px)')
);
```

Includes a polyfill for matchMedia that is installed through bower.

### CODE REVIEW

**Comment by ef4** [comment]
This is great. I PR'd a change to your branch switching from bower to npm.

It would also be nice to get something basic added to the docs if you have a chance. They live in the addon's sample app at `tests/dummy`.

**Comment by rlivsey** [comment]
Awesome :+1:

**Comment by mattgrannary** [comment]
Cool. I merged your changes. I'll see if I can get the documentation up tonight.

**Comment by mattgrannary** [comment]
Documentation in. Let me know if I missed anything or need to add a bit more explanation.

**Pull request merged**
