### PR TITLE
Remove error if no match found. Reduce matchBy scope

### PR DESCRIPTION
**Pull request by albertodotcom**
It is now possible to use `matchBy` in combination with `pick/pickOld/pickNew`  to reduce the jQuery context.
With this implementation it's possible to specify `pick`, `pickOld` and `pickNew` in the same transition, which can be confusing. Do we want to avoid that using an if statement so for instance if we have `pick` we skip `pickNew/pickOld` or throw an error or leave it as it is?

It is also possible to match by `id` and `class` and in those scenarios `#id` or `.class` will be used to pick the element in the DOM.

Finally if an attribute doesn't have a value, it just skips the element and resolves the promise. This relates to #233 . Do we want to log something in this scenario?

### CODE REVIEW

**Comment by ef4** [comment]
Thanks for this PR, apologies for the delay.

**Comment by albertodotcom** [comment]
My pleasure :smile: 
@ef4 would you like me to fix the merge conflicts and update the PR?

**Comment by ef4** [comment]
Yes, please do fix the conflicts. Feel free to merge or rebase as you prefer.

The conflicts are due to these other changes I've made to `explode`. I think the functionality should be complementary:

4b3757d3860303bf82c948dde583420d831c04e6
8732e20ad003847bd9c08de3cbf2fbc3e6f310cc
cbcc7dea8090d5d593321eded1a06d61eaccfa50

**Comment by albertodotcom** [comment]
Sorry for being late in updating my PR but I am on holiday :palm_tree: :smile:

**Comment by ef4** [comment]
No problem.

I needed part of this feature myself, see above commit. It would still be great to get your support for `matchBy: 'class'` and `matchBy: 'id'` though.

**Comment by albertodotcom** [comment]
Hi @ef4 is there something you would like me to do in order to get this PR merged?

**Comment by ef4** [comment]
Oh! I didn't notice your new commits, sorry. This looks good, thanks!

**Pull request merged**
