### PR TITLE
[Fastboot] Wrap velocity import in DOM guard

### PR DESCRIPTION
**Pull request by rondale-sc**
This should ensure that Velocity is still included in the final build
but doesn't blow up in fastboot.

This approach should be good, though I will likely do a PR to EmberCLI
soon that accomplishes the same thing with EmberApp#import so that you
could do:

`app.import('lol.js', { guardMissingDOM: true })`

### CODE REVIEW

**Comment by rwjblue** [comment]
Can you move the vendor files into a `liquid-fire` subdir (importing from the root of `vendor/` can lead to poor performance for certain ember-cli versions).

**Comment by rondale-sc** [comment]
@rwjblue sg

**Comment by rondale-sc** [comment]
Worked on a PR for EmberCLI for this, however, the approach taken here would not work with multiple imports so I instead used broccoli-stew#map to append them individually:

https://github.com/ember-cli/ember-cli/pull/5000/files

The solution in this PR should still work just fine for now.

**Comment by rwjblue** [comment]
Yes, I think pre-baked ember-cli support for this is key to having the ember addon ecosystem at large properly handle fastboot.

Using the mechanism here works well for liquid-fire across all ember-cli versions supported.

**Pull request merged**
